// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbISGd3eTjRfClz8HuszJZDL6WvwQtSs0',
    appId: '1:512858444455:web:d26bb2777511d92eb28182',
    messagingSenderId: '512858444455',
    projectId: 'simpletodo-19a48',
    authDomain: 'simpletodo-19a48.firebaseapp.com',
    storageBucket: 'simpletodo-19a48.firebasestorage.app',
    measurementId: 'G-HE88GW6EMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwOCD1LVbLHEUMapu_L5QNRXCC5Thka9k',
    appId: '1:512858444455:android:cf604cca1e2b00ddb28182',
    messagingSenderId: '512858444455',
    projectId: 'simpletodo-19a48',
    storageBucket: 'simpletodo-19a48.firebasestorage.app',
  );
}
